{{- if .Values.worker.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "prowler.fullname" . }}-worker
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
spec:
  {{- if .Values.worker.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.worker.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.worker.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prowler.fullname" . }}-worker
{{- end }}
