{{- if and .Values.worker.scanRecoveryCronJob.enabled .Values.worker.scanRecoveryCronJob.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prowler.scanRecovery.serviceAccountName" . }}
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
    app.kubernetes.io/component: scan-recovery
  {{- with .Values.worker.scanRecoveryCronJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.worker.scanRecoveryCronJob.serviceAccount.automount }}
{{- end }}
