apiVersion: v2
name: prowler
description: Prowler is an Open Cloud Security tool for AWS, Azure, GCP and Kubernetes. It helps for continuous monitoring, security assessments and audits, incident response, compliance, hardening and forensics readiness.
type: application
version: 1.1.0
appVersion: "5.5.1"
home: https://prowler.com/
icon: https://prowler.com/wp-content/themes/prowler-2024/img/web-logo-prowler-p.png
keywords:
  - security
  - aws
  - azure
  - gcp
  - kubernetes
maintainers:
  - name: Dani
    email: andre.gomes@promptlyhealth.com
