{{- if and .Values.neo4j.enabled .Values.neo4j.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prowler.neo4j.fullname" . }}
  labels:
    {{- include "prowler.neo4j.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.neo4j.persistence.accessMode }}
  {{- if .Values.neo4j.persistence.storageClass }}
  storageClassName: {{ .Values.neo4j.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.neo4j.persistence.size }}
{{- end }}
