{{- if and .Values.neo4j.enabled .Values.neo4j.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prowler.neo4j.serviceAccountName" . }}
  labels:
    {{- include "prowler.neo4j.labels" . | nindent 4 }}
  {{- with .Values.neo4j.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.neo4j.serviceAccount.automount }}
{{- end }}
