{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowler.neo4j.fullname" . }}
  labels:
    {{- include "prowler.neo4j.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neo4j.service.type }}
  ports:
    - name: bolt
      port: {{ .Values.neo4j.service.port }}
      targetPort: bolt
      protocol: TCP
    - name: http
      port: {{ .Values.neo4j.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "prowler.neo4j.selectorLabels" . | nindent 4 }}
{{- end }}
