apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prowler.fullname" . }}-worker-beat
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
spec:
  {{- if not .Values.worker_beat.autoscaling.enabled }}
  replicas: {{ .Values.worker_beat.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prowler.fullname" . }}-worker-beat
  template:
    metadata:
      annotations:
        # Pod Security Standards
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        # Checksums to trigger automatic pod restarts on config changes
        checksum/config: {{ include (print $.Template.BasePath "/api/configmap.yaml") . | sha256sum }}
        {{- if .Values.api.djangoConfigKeys.create }}
        {{- end }}
        {{- if .Values.postgresql.enabled }}
        checksum/secret-postgres: {{ include (print $.Template.BasePath "/api/secret-postgres.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.valkey.enabled }}
        checksum/secret-valkey: {{ include (print $.Template.BasePath "/api/secret-valkey.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.worker_beat.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "prowler.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "prowler.fullname" . }}-worker-beat
        # Pod Security Standards compliance label
        pod-security.kubernetes.io/enforce: restricted
        {{- with .Values.worker_beat.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.worker_beat.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prowler.worker_beat.serviceAccountName" . }}
      {{- with .Values.worker_beat.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker-beat
          {{- with .Values.worker_beat.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.worker_beat.image.repository }}:{{ .Values.worker_beat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker_beat.image.pullPolicy }}
          {{- with .Values.worker_beat.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker_beat.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "prowler.fullname" . }}-api
            {{- if .Values.api.djangoConfigKeys.create }}
            - secretRef:
                name: {{ include "prowler.fullname" . }}-api-django-config-keys
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - secretRef:
                name: {{ include "prowler.fullname" . }}-api-postgres
            {{- end }}
            {{- if .Values.valkey.enabled }}
            - secretRef:
                name: {{ include "prowler.fullname" . }}-api-valkey
            {{- end }}
            {{- with .Values.api.secrets }}
            {{- range $index, $secret := . }}
            - secretRef:
                name: {{ $secret }}
            {{- end }}
            {{- end }}
          {{- with .Values.worker_beat.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker_beat.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker_beat.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker_beat.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.worker_beat.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker_beat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker_beat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker_beat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
