{{- if .Values.worker_beat.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "prowler.fullname" . }}-worker-beat
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
spec:
  {{- if .Values.worker_beat.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.worker_beat.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.worker_beat.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.worker_beat.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prowler.fullname" . }}-worker-beat
{{- end }}
